Repository postechfiapgrupo04/check_lab, pull requests merged in 2024-01, with the labels that each got.

#4 [GRUPO-04] Create CheckLab Project
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/br/com/check/lab/CheckLabApplication.java
  src/test/java/br/com/check/lab/CheckLabApplicationTests.java
Labels: good first issue

#8 Task/estrutura basica projeto 02
  src/main/java/br/com/check/lab/CheckLabApplication.java
  src/main/java/br/com/check/lab/aplication/controller/AgendamentoController.java
  src/main/java/br/com/check/lab/controller/AgendamentoController.java
  src/main/java/br/com/check/lab/domain/entity/Agendamento.java
  src/main/java/br/com/check/lab/domain/entity/Exame.java
  src/main/java/br/com/check/lab/domain/entity/Paciente.java
  src/main/java/br/com/check/lab/domain/entity/TipoConfirmacao.java
  src/main/java/br/com/check/lab/exception/ControllerExceptionHandler.java
  src/main/java/br/com/check/lab/exception/NotFoundException.java
  src/main/java/br/com/check/lab/exception/StandardError.java
  src/main/java/br/com/check/lab/infrastructure/repository/AgendamentoRepository.java
  src/main/java/br/com/check/lab/infrastructure/repository/ExameRepository.java
  src/main/java/br/com/check/lab/infrastructure/repository/PacienteRepository.java
  src/main/java/br/com/check/lab/repository/AgendamentoRepository.java
  src/main/java/br/com/check/lab/service/AgendamentoService.java
  src/main/java/br/com/check/lab/service/InicializarDadosTeste.java
Labels: enhancement, Story

#7 Ajustando README
  README.md
Labels: documentation, enhancement

#11 Task/inserindo dados arquivo datasql
  src/main/java/br/com/check/lab/CheckLabApplication.java
  src/main/java/br/com/check/lab/domain/entity/Agendamento.java
  src/main/java/br/com/check/lab/service/InicializarDadosTeste.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: Story
